# .github/release.yml

changelog:
  exclude:
    labels:
      - ci
      - documentation
      - invalid
      - question
      - wontfix
      - duplicate
      - good first issue
      - help wanted
    authors:
      - octocat
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"