# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.7.0
        with:
          arguments: shadowJar

      - name: Rename artifact to use tag as version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mv build/libs/*.jar build/libs/archivist-${{github.ref_name}}.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/v')
        id: artifact
        with:
          name: artifact
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: build/libs

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          generate_release_notes: true          
          files: |
            build/libs/*.jar
